//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baiguzin_Глазки_save
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Media;
    using System.Windows.Navigation;

    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int AgentTypeID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string AgentTypeString => AgentType.Title;


        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }


        public int skidka => Sale();
        public int Sale()
        {
            var productSale = Baiguzin_glazkiEntities.GetContext().ProductSale.Where(p => p.AgentID == ID).ToList();
            var products = Baiguzin_glazkiEntities.GetContext().Product.ToList();
            decimal sale = 0;
            int skidka = 0;
            foreach (var product in products)
            {
                foreach (var item2 in productSale)
                {
                    if (product.ID == item2.ProductID)
                    {
                        sale += product.MinCostForAgent * item2.ProductCount;
                    }
                }
            }
            if (sale >= 0 && sale < 10000)
                skidka = 0;
            if (sale >= 10000 && sale < 50000)
                skidka = 5;
            if(sale >=50000 && sale<150000)
                skidka = 10;
            if (sale >= 150000 && sale < 500000)
                skidka = 20;
            if(sale>=500000)
                skidka = 25;
            return skidka;
        }
        
        public int ProductCount => GetAllProducts();
        public int GetAllProducts()
        {
            var count = 0;
            var context = Baiguzin_glazkiEntities.GetContext().ProductSale.Where(p => p.AgentID == ID).ToList();
            foreach (var productSale in context)
            {
                count += productSale.ProductCount;
            }

            return count;
        }



        public SolidColorBrush FontStyle
        {
            get
            {
                if (skidka >=10)
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("LightGreen");
                }
                else
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("White");
                }
            }
        }

    }
}
